Update dag

diff --git a/dag b/dag
--- a/dag
+++ b/dag
@@ -6,15 +6,18 @@ blu='\033[1;36m'
 pnk='\033[1;35m'
 clr='\033[0m'
 
-version="1.42"
-changes=" - Filebeat checking status\n- ref: https://github.com/zaemliss/Constellation/commit/882305a8f62f9613d672d966e91b5b20bb6f9193"
+version="1.43"
+changes=" - Optimized getting External IP\n- Added search parameter to log view\n- ref: https://github.com/zaemliss/Constellation/commit/882305a8f62f9613d672d966e91b5b20bb6f9193"
 
-echo -ne "${grn} getting external IP address... ";
-EXTERNAL_HOST_IP=$(curl -s https://api.ipify.org)
-echo -e "${yel}$EXTERNAL_HOST_IP ${clr}";
+# Only get external IP if needed
+if [[ $1 == "" || $1 == "restart" || $1 == "reset" || $1 == "join" || $1 == "leave" ]]; then
+        echo -ne "${grn} getting external IP address... ";
+        EXTERNAL_HOST_IP=$(curl -s https://api.ipify.org)
+        echo -e "${yel}$EXTERNAL_HOST_IP ${clr}";
+fi
 
 DAGDIR=$HOME/constellation
- 
+
 
 # Declare Functions #################################
 function checkVersion()
@@ -46,7 +49,7 @@ function showStatus()
         else
                 echo -e "${blu} Web Status      : ${red}offline${clr}"
         fi
-        
+
         # Is the screen containing the node execution active?
         chkScreen=$(screen -ls | grep dag)
         if [ -z "$chkScreen" ]; then
@@ -54,7 +57,7 @@ function showStatus()
         else
                 echo -e "${blu} Node Status     : ${grn}online${clr}"
         fi
-        
+
         # is FileBeat running>
         chkFileBeat=$(pgrep filebeat)
         if [ -z "$chkFileBeat" ]; then
@@ -75,7 +78,7 @@ function showHelp()
         echo -e " ${yel} dag status         ${blu}shows you the live node output ${clr}"
         echo -e " ${yel} dag join ip_addr   ${blu}joins to node specified in ip_addr ${clr}"
         echo -e " ${yel} dag leave          ${blu}leaves the cluster ${clr}"
-        echo -e " ${yel} dag logs           ${blu}displays the app logs in real time${clr}"
+        echo -e " ${yel} dag logs [search]  ${blu}displays the app logs in real time OR if a parameter is supplied, returns matching results in ${grn}search${clr}"
         echo
         echo -e " ${grn}you can navigate to your node via web browser by entering ${blu}http://$EXTERNAL_HOST_IP:9000 ${grn}in the address bar.${clr}"
         echo
@@ -84,14 +87,18 @@ function showHelp()
 function showLogs()
 {
         echo
-        echo -e "${grn} This will show you the current logs. Once you see the node output, exit by pressing ${blu}CTRL-C"
-        echo -e "${grn} This only shows the logs and does not interact with the node.${clr}"
-        read -e -p " Press [ENTER] to continue or N to cancel: " CHOICE
-        if [[ ("$CHOICE" == "n" || "$CHOICE" == "N") ]]; then
-        echo -e "${yel} Aborted... ${clr}"
-        exit 1;
+        if [[ $2 != "" ]]; then
+            cat $DAGDIR/logs/app.log | grep -i $2
+        else
+            echo -e "${grn} This will show you the current logs. Once you see the node output, exit by pressing ${blu}CTRL-C"
+            echo -e "${grn} This only shows the logs and does not interact with the node.${clr}"
+            read -e -p " Press [ENTER] to continue or N to cancel: " CHOICE
+            if [[ ("$CHOICE" == "n" || "$CHOICE" == "N") ]]; then
+                echo -e "${yel} Aborted... ${clr}"
+                exit 1;
+            fi
+            tail -f $DAGDIR/logs/app.log
         fi
-        tail -f $DAGDIR/logs/app.log
 }
 
 function enterScreen()
@@ -179,7 +186,7 @@ if [[ $1 == "status" ]]; then
 fi
 
 if [[ $1 == "logs" ]]; then
-        showLogs
+        showLogs $1 $2 $3
 fi
 
 if [[ $1 == "" ]]; then
