Update dag

diff --git a/dag b/dag
--- a/dag
+++ b/dag
@@ -26,14 +26,27 @@ function showHelp()
         echo
 }
 
+function showLogs()
+{
+        echo
+        echo -e "${grn} This will show you the current logs. Once you see the node output, exit by pressing ${blu}CTRL-C"
+        echo -e "${grn} This only shows the logs and does not interact with the node.${clr}"
+        read -e -p "Press [ENTER] to continue or N to cancel: " CHOICE
+        if [[ ("" == "n" || "" == "N") ]]; then
+        echo -e "${yel} Aborted... ${clr}"
+        exit 1;
+        fi
+        tail -f $DAGDIR/logs/app.log
+}
+
 function enterScreen()
 {
         echo
-        echo -e "\033[1;31m IMPORTANT: \033[1;32monce in the screen where you see the node output, exit by pressing \033[1;36mCTRL-A \033[1;32mthen \033[1;36mCTRL-D"
-        echo -e "\033[1;32m Do \033[1;31mNOT \033[1;32mpress \033[1;36mCTRL-C \033[1;32munless you are trying to stop the node!\033[0m"
+        echo -e "${red} IMPORTANT: ${grn}once in the screen where you see the node output, exit by pressing ${blu}CTRL-A ${grn}then ${blu}CTRL-D"
+        echo -e "${grn} Do ${red}NOT ${grn}press ${blu}CTRL-C ${grn}unless you are trying to stop the node!${clr}"
         read -e -p "Press [ENTER] to continue or N to cancel: " CHOICE
         if [[ ("" == "n" || "" == "N") ]]; then
-        echo -e "\033[1;33m Aborted... \033[0m"
+        echo -e "${yel} Aborted... ${clr}"
         exit 1;
         fi
         screen -x dag
