Update dag
added swapadd

diff --git a/dag b/dag
--- a/dag
+++ b/dag
@@ -7,7 +7,7 @@ yel='\033[1;33m'
 blu='\033[1;36m'
 pnk='\033[1;35m'
 clr='\033[0m'
-DAG_VERSION="2.87"
+DAG_VERSION="2.88"
 
 function checkVersion()
 {
@@ -188,6 +188,28 @@ function makeswap()
   free
   echo
 }
+
+function swapadd()
+{
+  echo
+  echo -e "${blu}Increasing Swap...${clr}"
+  free
+  echo
+  read -e -p " How many Gigs do you want to add (CTRL-C to cancel): " CHOICE
+  if [[ ! -z $CHOICE ]]; then
+        sudo swapoff /swapfile
+        sudo dd if=/dev/zero of=/swapfile bs=1M count=$(( CHOICE*1024 )) oflag=append conv=notrunc
+        sudo mkswap /swapfile
+        sudo swapon /swapfile
+        echo -e "${yel}${CHOICE}G swapfile resized...${clr}"
+        free
+        echo
+  else
+        echo -e "${red} Quantity can't be empty! Aborting. ${clr}"
+        exit 1
+  fi
+}
+
 function showStatus()
 {
         # Can I see the webpage?
@@ -624,6 +646,10 @@ fi
 
 if [[ $1 == "makeswap" ]]; then
         makeswap
+fi
+
+if [[ $1 == "swapadd" ]]; then
+        swapadd
 fi
 
 if [[ $1 == "metrics" ]]; then
