fix keystore generation

diff --git a/dag b/dag
--- a/dag
+++ b/dag
@@ -369,15 +369,15 @@ function doInstall()
                         goodPass=0
                 fi
         done
-	
-	echo -e "${blu}4. ${grn}Please enter an alias for the node (e.x.: myalias) :${clr}"
+
+        echo -e "${blu}4. ${grn}Please enter an alias for the node (e.x.: myalias) :${clr}"
         read -e -p "Please enter the Alias for the node :" MYNODEALIAS
         export NODEALIAS=$MYNODEALIAS
 
         echo -ne "${blu}5. ${grn}Do you already have a p12 file you'd like to use? [y/n] :${clr}"
         read -e -p ": " YN
         echo
-	OWNFILE=0
+        OWNFILE=0
         if [[ "$YN" == "y" ]] || [[ "$YN" == "Y" ]];then
                 goodFile=0
                 while [[ "$goodFile" -ne "1" ]]
@@ -388,21 +388,21 @@ function doInstall()
                                 echo
                                 goodFile=0
                         else
-                                goodFile=1
-                                export KEYSTORE=$P12FILE
-				java -jar $dagDir/cl-keytool.jar --keystore $KEYSTORE --alias $NODEALIAS --storepass $STOREPASS --keypass $KEYPASS
-        				if [ $? -ne 0 ]; then
-                				echo -e "${red}KeyStore generation failed! please check the information you supplied and try again:${clr}"
-                				exit 1
-        				else
-                				echo -e "${grn}KeyStore generation success! ${clr}"
-        				fi
-			fi
+                            export KEYSTORE=$P12FILE
+                            goodFile=1
+                        fi
                 done
         else
-                        read -e -p "please enter the FULL path of the p12 file you want to create. e.x.: /root/constellation/testfile.p12 :" P12FILE
-                        export KEYSTORE=$P12FILE
-			OWNFILE=1
+                read -e -p "please enter the FULL path of the p12 file you want to create. e.x.: /root/constellation/testfile.p12 :" P12FILE
+                export KEYSTORE=$P12FILE
+                java -jar $dagDir/cl-keytool.jar --keystore $KEYSTORE --alias $NODEALIAS --storepass $STOREPASS --keypass $KEYPASS
+                if [ $? -ne 0 ]; then
+                        echo -e "${red}KeyStore generation failed! please check the information you supplied and try again:${clr}"
+                        exit 1
+                else
+                        echo -e "${grn}KeyStore generation success! ${clr}"
+                fi
+                OWNFILE=1
         fi
         
         export CL_STOREPASS=$STOREPASS
@@ -424,7 +424,7 @@ function doInstall()
                         echo
                         echo -e "${red}Joining node ${yel}$GENESIS ${red}failed! ${clr}"
                         echo -e "check to be certain you are on the whitelist and the IP address of the genesis node is valid."
-			echo
+                        echo
                 fi
         fi
 
