Update dag-testnet
added dependency check for locate

diff --git a/dag-testnet b/dag-testnet
--- a/dag-testnet
+++ b/dag-testnet
@@ -14,7 +14,7 @@ yel='\033[1;33m'
 blu='\033[1;36m'
 pnk='\033[1;35m'
 clr='\033[0m'
-DAG_VERSION="1.0"
+DAG_VERSION="1.01"
 
 function checkVersion()
 {
@@ -128,6 +128,24 @@ function checkDepends()
                         HAVEGED_INSTALL_CMD="sudo apt install -y haveged -qq"
                     elif [[ "$OS_DIST" == "RedHat" ]]; then
                         HAVEGED_INSTALL_CMD="sudo yum install -y haveged"
+                    fi
+                    echo -e " ${pnk}Installing latest version of Haveged...${clr}"
+                    $HAVEGED_INSTALL_CMD > /dev/null 2>&1
+                    if [ $? -ne 0 ]; then
+                            echo -e "${red}Installation failed! please run manually and check for errors:${clr}"
+                            echo -e "${blue}$HAVEGED_INSTALL_CMD${clr}"
+                            echo
+                            exit 1
+                    fi
+            fi
+        fi
+        if [[ "$OS" == "Linux" ]]; then
+            locateinstalled=$(which locate)
+            if [[ -z "$locateinstalled" ]]; then
+                    if [[ "$OS_DIST" == "Debian" ]]; then
+                        HAVEGED_INSTALL_CMD="sudo apt install -y locate -qq"
+                    elif [[ "$OS_DIST" == "RedHat" ]]; then
+                        HAVEGED_INSTALL_CMD="sudo yum install -y locate"
                     fi
                     echo -e " ${pnk}Installing latest version of Haveged...${clr}"
                     $HAVEGED_INSTALL_CMD > /dev/null 2>&1
