Update install-filebeat

diff --git a/install-filebeat b/install-filebeat
--- a/install-filebeat
+++ b/install-filebeat
@@ -50,6 +50,16 @@ function extractCerts()
       CERTPWD="$CERTPWD$pass"
     fi
   done
+  echo -e "${grn} extracting certs ..."
+  openssl pkcs12 -in $certfile -password pass:$CERTPWD -nocerts -nodes > client.key
+  openssl pkcs12 -in $certfile -password pass:$CERTPWD -clcerts -nokeys > client.cer
+  openssl pkcs12 -in $certfile -password pass:$CERTPWD -cacerts -nokeys -chain > client-ca.cer
+  if [[ $? -ne 0 ]]; then
+    echo -e "${red} ERROR - wrong password or general failure. Please check your password and start over. ${clr}"
+    echo -e "${red} Installation Aborted.${clr}"
+    echo
+    exit 1
+  fi
 }
 
 
